name: ci

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    uses: bjuvensjo/.github/.github/workflows/python-poetry-ci.yml@main
    with:
      cov: vang
      src: vang
      runs-on: '["ubuntu-latest"]'
      version: '["3.11"]'
